name: check-n-transform

on:
    push

jobs:
    transform-csv:
        runs-on: ubuntu-latest
        steps:
            - name: perform checkout
              uses: actions/checkout@v4
            - name: validate csv
              run: python scripts/check-n-transform/validate-csv.py
            - name: transform csv
              run: python scripts/check-n-transform/img2doc-csv.py
            - name: commit output csv
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: output csv written
    update-jupyter-notebook:
        runs-on: ubuntu-latest
        steps:
            - name: perform checkout
              uses: actions/checkout@v4
            - name: install nbconvert and jupyter dependencies
              run: pip install -r scripts/update-ipynb/requirements.txt
            - name: update notebook
              run: python scripts/update-ipynb/update-ipynb.py
            - name: commit tmp xmls
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: notebook updated