name: check-n-transform

on:
    push

jobs:
    transform-csv:
        runs-on: ubuntu-latest
        steps:
            - name: perform checkout
              uses: actions/checkout@v4
            - name: validate csv
              run: python scripts/check-n-transform/validate-csv.py
            - name: transform csv
              run: python scripts/check-n-transform/img2doc-csv.py
            - name: commit output csv
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: output csv written

    update-notebook:
      needs: transform-csv  # Ensure this job only runs after 'transform-csv' completes successfully
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        # List all files and directories to confirm structure
        - name: List files (debugging step)
          run: ls -R  # List all files and directories recursively

        # Change directory to the root of the repository just in case
        - name: Change to repo root (debugging step)
          run: cd ${{ github.workspace }} && pwd && ls

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pandas jupyter matplotlib

        # Run the Jupyter notebook
        - name: Run Jupyter Notebook
          run: |
            cd metadata/ipynb
            jupyter nbconvert --to notebook --execute output_doc_id.ipynb --output output_doc_id.ipynb

        # Check if the notebook has changes
        - name: Check if notebook has changes
          id: check_changes
          run: git diff --exit-code metadata/ipynb/output_doc_id.ipynb || echo "Notebook changed"

        # Commit the changes only if there are any
        - name: Commit ipynb update
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "ipynb updated"
