name: check-n-transform

on:
    push

jobs:
    transform-csv:
        runs-on: ubuntu-latest
        steps:
            - name: perform checkout
              uses: actions/checkout@v4
            - name: validate csv
              run: python scripts/check-n-transform/validate-csv.py
            - name: transform csv
              run: python scripts/check-n-transform/img2doc-csv.py
            - name: install dependencies
              run: pip install -r scripts/metadata-analysis/requirements.txt
            - name: analyze metadata
              run: python scripts/metadata-analysis/metadata-analysis.py
            - name: commit output csv
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: output csv written