name: img2doc-csv

on:
    push

jobs:
    transform-csv:
        runs-on: ubuntu-latest
        steps:
            - name: sleep for 15s
              uses: juliangruber/sleep-action@v2.0.0
              with:
                time: 20s
            - name: perform checkout
              uses: actions/checkout@v4
            - name: validate csv
              run: python scripts/img2doc-csv/validate-csv.py
            - name: transform csv
              run: python scripts/img2doc-csv/img2doc-csv.py
            - name: commit transformed csv
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: transformed csv img2doc